services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
    networks:
      - library-library-backend_default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jaybird9er@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    networks:
      - library-library-backend_default
    ports:
      - '80:80'
    depends_on:
      - database

  db_ui:
    image: shyim/adminerevo
    ports:
      - target: 8080
        published: 8080
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DB: ecommerce
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_PASSWORD: root
      ADMINER_DESIGN: dracula
    networks:
      - library-library-backend_default

volumes:
  data:
networks:
  library-library-backend_default:
    driver: bridge
    name: library-library-backend_default